# Generated by Django 5.2 on 2025-04-30 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('income_source', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('BUSINESS INCOME', 'Business Income'), ('INVESTMENTS', 'Investments'), ('MULTIPLE', 'Multiple'), ('OTHER', 'Other')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
